version: "3.2"

# for KillBill
volumes:
  db:

services:
  # Kafka containers for integration tests
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    expose:
      - ${ZOOKEEPER_PORT}
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_CREATE_TOPICS: "${KB2KAFKA_TOPIC}:1:1"

  # KillBill containers for integration tests
  killbill:
    image: killbill/killbill:0.22.26
    container_name: killbill
    hostname: killbill
    ports:
      - 8080:8080
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml

  db:
    image: killbill/mariadb:0.22
    container_name: kb_db
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill

  kaui:
    image: killbill/kaui:2.0.9
    container_name: kaui
    ports:
      - 9090:8080
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080

  # KillBill to Kafka event adapter
  kb2kafka:
    build: .
    container_name: kb2kafka-event-adapter
    hostname: kb2kafka
    ports:
      - ${KB2KAFKA_LISTENER_PORT}:${KB2KAFKA_LISTENER_PORT}
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:${KAFKA_PORT}
      KAFKA_TOPIC_NAME: ${KB2KAFKA_TOPIC}
      KAFKA_GROUP_ID: ${KB2KAFKA_GROUP}
      KAFKA_RESPONSE_TOPIC_NAME: response-test-topic
      KAFKA_BROKER_HEALTHCHECK_URL: http://kafkahealthcheck:${HEALTHCHECK_PORT}
      KAFKA_CLUSTER_HEALTHCHECK_URL: http://kafkahealthcheck:${HEALTHCHECK_PORT}/cluster
      LISTENER_ADDRESS: :${KB2KAFKA_LISTENER_PORT}
      LISTENER_PATH: ${KB2KAFKA_LISTENER_URL_PATH}

  kafka-health-check:
    build: ./infrastructure
    container_name: kafka-health-check
    depends_on:
      - kb2kafka
    hostname: kafkahealthcheck
    ports:
      - ${HEALTHCHECK_PORT}:${HEALTHCHECK_PORT}
    command: ["/app/kafka-health-check-master/kafka-health-check",
              "-zookeeper=zookeeper:${ZOOKEEPER_PORT}", "-broker-host=kafka", "-broker-port=${KAFKA_PORT}",
              "-broker-id=1001", "-check-interval=10s", "-server-port=${HEALTHCHECK_PORT}"]
