version: "3.2"

# for KillBill
volumes:
  db:

services:
  # Kafka containers
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"

  # KillBill containers
  killbill:
    image: killbill/killbill:0.22.26
    container_name: killbill
    hostname: killbill
    ports:
      - "8080:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml

  db:
    image: killbill/mariadb:0.22
    container_name: kb_db
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill

  kaui:
    image: killbill/kaui:2.0.9
    container_name: kaui
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080

  # KillBill to Kafka event adapter
  kb2kafka:
    build: .
    container_name: kb2kafka-event-adapter
    hostname: kb2kafka
    ports:
      - "8082:8082"
    environment:
      DEBUG: 'true'
      PORT: 8082
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_TOPIC_NAME: test-topic
      KAFKA_GROUP_ID: group-id-1
      KAFKA_RESPONSE_TOPIC_NAME: response-test-topic
      LISTENER_ADDRESS: :8082
      LISTENER_PATH: /callmeback
#TODO 8082 in two places

